spring.datasource.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/clinica_odontologica?useSSL=true&requireSSL=true&serverTimezone=-05:00&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=8iHGmWCheGEgJTS.root
spring.datasource.password=03YEUnE5ZpGhiazT

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web.filter=ERROR

logging.level.io.jsonwebtoken=ERROR