name: Despertar Backend Diario

on:
  schedule:
    - cron: '0 12 * * 1-6'
  workflow_dispatch:

jobs:
  despertar:
    runs-on: ubuntu-latest

    steps:
      - name: Ping al servidor
        run: curl --max-time 120 https://clinica-odontologica-1-5uyo.onrender.com/api/health
