name: Mantener Backend Render Activo

on:
  schedule:
    - cron: '13 11 * * 1-6'
    
  workflow_dispatch: 

jobs:
  ping-al-servidor:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar al endpoint de Health Check
        run: curl --max-time 300 https://clinica-odontologica-1-5uyo.onrender.com/api/health